[id='pipeline-task-syntax_{context}']
= Task syntax

To define a configuration file for a `Task` resource, specify the following fields:

*Required*:

* `apiVersion` - Specifies the API version.
* `kind` - Specify the `Task` resource object
* `metadata` - Specifies data to uniquely identify the `Task` resource object, for example a `name`.
* `spec` - Specifies the configuration information for the `Task` resource object. `Task` steps must be defined.
    the following fields:
** link:https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#steps[`steps`] - Specifies one or more container images that run in your `Task`.


*_Optional_*:

* link:https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#inputs[`inputs`] - Specifies parameters and `PipelineResources` needed by your `Task`. A `Task` can declare the inputs it needs, which can be either or both:

** link:https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#parameters[`parameters`]
** link:https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#input-resources[input resources] 
 
* link:https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#steps[`outputs`] - Specifies `PipelineResources` created by your `Task`
* link:https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#volumes[`volumes`] - Specifies one or more volumes that you want to make available to your `Task` steps.
* link:https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#step-template[`stepTemplate`] - Specifies a `Container` step definition to use as the basis for all steps in a `Task`.



The following example shows a configured YAML file where the fields are completed:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: example-task-name
spec:
  inputs:
    resources:
      - name: workspace
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
        default: /workspace/workspace/Dockerfile
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: openshift-example
      image: openshift
      args: ["openshift-build-example", "SECRETS-example.md"]
    - image: gcr.io/example-builders/build-example
      command: ["echo"]
      args: ["$(inputs.params.pathToDockerFile)"]
    - name: dockerfile-pushexample
      image: gcr.io/example-builders/push-example
      args: ["push", "$(outputs.resources.builtImage.url)"]
      volumeMounts:
        - name: docker-socket-example
          mountPath: /var/run/docker.sock
  volumes:
    - name: example-volume
      emptyDir: {}
```

== Additional resources
* To learn more about configuring files for a `Task` resource, read about link:https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#required-fields[Required Fields].