[id="openshift-pipelines_{context}"]
= OpenShift Pipelines

//:FeatureName: OpenShift Pipelines
//include::modules/technology-preview.adoc[leveloffset=+1]

OpenShift Pipelines is a cloud-native, continuous integration and continuous delivery (CI/CD) solution based on Kubernetes resources. It uses link:https://tekton.dev[Tekton] building blocks to automate deployments across multiple platforms by abstracting away the underlying implementation details. Tekton introduces a number of standard link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resource Definitions (CRDs)] for defining pipelines that are portable across Kubernetes distributions.

== Key features

* OpenShift Pipelines are designed for decentralized teams that work on microservice based architecture.
* OpenShift Pipelines use standard CI/CD pipeline definitions that are easy to extend and integrate with the existing Kubernetes tools, enabling you to scale on-demand.
* You can use Openshift Pipelines to build images with Kubernetes tools such as Source-to-Image (S2I), Buildah, Buildpacks, and Kaniko that are portable across any Kubernetes platform.
* You can use the OpenShift Developer Console to create Tekton resources, view logs of pipeline runs, and manage pipelines under your OpenShift project namespaces.


== Additional resources

* For more details on defining pipelines, see the link:https://openshift.github.io/pipelines-docs/docs/0.10.5/assembly_using-pipelines.html[Using Pipelines documentation].
* For more information on Tekton see the link:https://github.com/tektoncd[Tekton Pipelines documentation].
* Visit our link:https://github.com/openshift/pipelines-docs[GitHub] repository for more information or to contribute.
