// Ths module is included in the following assembly:
//
// assembly_using-openshift-pipelines.adoc

[id="defining-and-creating-pipelineresources_{context}"]
= Defining and creating pipeline resources

`PipelineResources` are artifacts that are used as inputs to a `Task` and can be output by a `Task`.

[discrete]
=== Procedure

After you create `Task`s, create `PipelineResources` that contain the specifics of the Git repository and the image registry to be used in the `Pipeline` during execution as follows:

. Create a `resources.yaml` file and with the `PipelineResource`s that contain the specifics of the Git repository and the image registry to be used in the pipeline during execution.

.. Create a `PipelineResource` that defines the Git repository for the frontend application:
+
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: ui-repo
spec:
  type: git
  params:
    - name: url
      value: http://github.com/openshift-pipelines/vote-ui.git
----

.. Create a `PipelineResource` that defines the OpenShift internal image registry to which you want to push the frontend image:
+
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: ui-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/ui:latest
----

.. Create a `PipelineResource` that defines the Git repository for the backend application:
+
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: api-repo
spec:
  type: git
  params:
    - name: url
      value: http://github.com/openshift-pipelines/vote-api.git
----

.. Create a `PipelineResource` that defines the OpenShift internal image registry to which you want to push the backend image:
+
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: api-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/api:latest
----

. Create the Pipeline Resources:
+
----
$ oc create -f https://raw.githubusercontent.com/openshift/pipelines-tutorial/master/pipeline/resources.yaml
----

. See the list of resources:
+
----
$ tkn resource ls

NAME        TYPE    DETAILS
api-repo    git     url: http://github.com/openshift-pipelines/vote-api.git
ui-repo     git     url: http://github.com/openshift-pipelines/vote-ui.git
api-image   image   url: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/api:latest
ui-image    image   url: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/ui:latest
----

////
[discrete]
== Additional resources

* A bulleted list of links to other material closely related to the contents of the procedure module.
* For more details on writing procedure modules, see the link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
* Use a consistent system for file names, IDs, and titles. For tips, see _Anchor Names and File Names_ in link:https://github.com/redhat-documentation/modular-docs#modular-documentation-reference-guide[Modular Documentation Reference Guide].
////
