[id="openshift-pipelines-release-notes"]
= Release Notes for OpenShift Pipelines 0.8 Developer Preview
:context: openshift-pipelines-release-notes-0.8


OpenShift Pipelines is a cloud-native CI/CD experience based on the Tekton project, which provides:

* Standard Kubernetes-native pipeline definitions (CRDs)
* Serverless pipelines with no CI server management overhead
* Extensibility to build images using any Kubernetes tool, such as S2I, buildah, JIB, and Kaniko.
* Portability across any Kubernetes distribution
* Powerful CLI for interacting with pipelines
* Integrated user experience with the OpenShift Console developer perspective

For an in-depth walk-through of OpenShift Pipelines, follow this link:https://github.com/openshift/pipelines-tutorial/[tutorial] to build your first cloud-native pipeline. See the link:https://openshift.github.io/pipelines-docs/docs/docs/index.html[OpenShift Pipelines documentation] to learn the details.

== Notable Features
In addition to the fixes and stability improvements, here is a highlight of what is new in OpenShift Pipelines 0.8:

* Support for specifying "0" as no-timeout for PipelineRuns.
* Support to enable `pipelineSpec` and `resourceSpec` in the `PipelineRun` spec
* Auto configures a service account (pipeline) for running pipelines that is able to build and push images into the OpenShift internal image registry
* Supports multiple SSH keys for the same host
* Ships most commonly used ClusterTasks for S2I, Buildah and OpenShift-Client
* Ships Tetkon-Triggers v0.1.0 for running pipelines based on Git webhooks
* PipelineRun and TaskRun metrics in the OpenShift monitoring stack (Prometheus)
* CLI commands for interacting directly with Tasks and TaskRuns


== Getting support

[discrete]
=== Product
If you find an error, encounter a bug or have suggestions for improving the functionality of OpenShift Pipelines, file an issue in the link:https://github.com/openshift/tektoncd-pipeline-operator[Tektoncd Pipeline Operator] repository.

Provide as many details in the description of the issue as possible.

[discrete]
=== Documentation
If you find an error or have suggestions for improving the documentation, file an issue in link:https://github.com/openshift/pipelines-docs[pipelines documentation] repository.

[discrete]
=== Getting in touch with the product team
For questions and feedback subscribe to the link:mailto:pipelines-interest@redhat.com[pipelines-interest@redhat.com]  mailing list or join the link:https://coreos.slack.com/messages/CG5GV6CJD[#tektoncd-pipelines] channel on CoreOS Slack.

== Deprecated features

The following items are deprecated in 0.8.0, and will be removed in the next release (0.9.0):

* The *Name* and *Digest* fields on `TaskRunStatus.ResourcesResult` are deprecated.
* `ServiceAccountName(s)` replaces `ServiceAccount(s)`, `ServiceAccount` and `ServiceAccounts` fields (on TaskRun and PipelineRun) are deprecated.

== Known Issues

* https://jira.coreos.com/browse/ODC-2464[ODC-2464]: The pipeline graph displays tasks out of order which doesn't match the execution.

== Fixed Issues

* link:https://jira.coreos.com/browse/ODC-2064[ODC-2064]: Starting a pipeline using the OpenShift Console Developer perspective generates a deprecated field in the resulting PipelineRun which prevents the pipeline from starting.
* https://jira.coreos.com/browse/ODC-1847[ODC-1847]: OpenShift Pipelines can now be started using the OpenShift Console Developer perspective.
