[id="openshift-pipelines-release-notes"]
= Openshift Pipelines 0.7 Developer Preview Release Notes
:context: openshift-pipelines-release-notes-0.7


OpenShift Pipelines is a cloud-native CI/CD experience based on the Tekton project, which provides:

* Standard Kubernetes-native pipeline definitions (CRDs)
* Serverless pipelines with no CI server management overhead
* Extensibility to build images using any Kubernetes tool, such as S2I, buildah, JIB, and Kaniko.
* Portability across any Kubernetes distribution
* Powerful CLI for interacting with pipelines
* Integrated user experience with the OpenShift Console developer perspective

To work with OpenShift Pipelines, access an OpenShift 4.2 cluster using cloud.openshift.com or rhpds.redhat.com or download CodeReady Containers. Download Tekton CLI, and run the following commands to create a sample pipeline that uses S2I for building and deploying a Java application:

----
$ oc create -f http://bit.ly/pipelines-demo
$ tkn pipeline start petclinic-pipeline -n pipelines-demo
$ tkn pipeline logs -f
----

For an in-depth walk-through of OpenShift Pipelines, follow this link:https://github.com/openshift/pipelines-tutorial/[tutorial] to build your first cloud-native pipeline. See the link:https://openshift.github.io/pipelines-docs/docs/docs/index.html[OpenShift Pipelines documentation] to learn the details.

== Notable Features
In addition to the fixes and stability improvements, here is a highlight of what is new in OpenShift Pipelines 0.7:

*Side-cars in Tasks:* Run side-cars alongside the steps in a task to provide auxiliary functions, for example, a mock API for testing an application.

*Third-party notifications:* Notify third-party systems on completion of a task using CloudEvents that contain the complete details of the task execution as the payload.

*Pipelines in OpenShift Console:* Pipelines are now available in the OpenShift 4.2 web console in the Developer perspective to start pipelines, visually interact with them and inspect logs.

*New Tekton CLI commands:* Explore new commands for various features, such as brew installation, interactive mode for starting pipelines, providing inputs to the pipeline, canceling and deleting commands.

== Getting support

[discrete]
=== Product
If you find an error, encounter a bug or have suggestions for improving the functionality of OpenShift Pipelines, file an issue in the link:https://github.com/openshift/tektoncd-pipeline-operator[Tektoncd Pipeline Operator] repository.

Provide as many details in the description of the issue as possible.

[discrete]
=== Documentation
If you find an error or have suggestions for improving the documentation, file an issue in link:https://github.com/openshift/pipelines-docs[pipelines documentation] repository.

[discrete]
=== Getting in touch with the product team
For questions and feedback subscribe to the link:mailto:pipelines-interest@redhat.com[pipelines-interest@redhat.com]  mailing list or join the link:https://coreos.slack.com/messages/CG5GV6CJD[#tektoncd-pipelines] channel on CoreOS Slack.

== Known Issues

* link:https://jira.coreos.com/browse/ODC-2064[ODC-2064]: Starting a pipeline using the OpenShift Console Developer perspective generates a deprecated field in the resulting PipelineRun which prevents the pipeline from starting.

* link:https://jira.coreos.com/browse/ODC-1847[ODC-1847]: Starting a pipeline using the OpenShift Console Developer perspective uses the `default` service account for starting the pipeline and hence requires the user to give sufficient privileges to the `default` service account. The fix is already applied upstream by running pipelines with a preconfigured `pipeline` service account which has sufficient privileges.

== Fixed Issues

* link:https://jira.coreos.com/browse/SRVKP-283[SRVKP-283] - CLI: Sort pipelineruns in descending start time in interactive log.
* link:https://jira.coreos.com/browse/SRVKP-302[SRVKP-302] - CLI: Pipeline logs command should sort on time started
